export type ScanStatus = 'running' | 'completed' | 'failed' | 'queued';
export type DocStatus = 'verified' | 'needs_review' | 'auto_fixed';
export type CorrectionStatus = 'pending' | 'approved' | 'rejected';
export type PRStatus = 'open' | 'merged' | 'closed';
export type LogLevel = 'info' | 'warning' | 'error';

export interface Repository {
  id: string;
  name: string;
  fullName: string;
  language: string;
  languageColor: string;
  avatar: string;
  stars: number;
  health: number;
  coverage: number;
  lastScan: string;
  branch: string;
  docSections: number;
  codeChunks: number;
}

export interface StatCard {
  id: string;
  label: string;
  value: string | number;
  trend: number;
  trendLabel: string;
  sparkline: number[];
  icon: string;
  color: string;
}

export interface ScanRun {
  id: string;
  repository: string;
  repoId: string;
  status: ScanStatus;
  duration: number;
  filesChanged: number;
  meaningfulChanges: number;
  sectionsChecked: number;
  aiFixes: number;
  progress: number;
  startedAt: string;
  completedAt: string;
  baseSha: string;
  headSha: string;
  prNumber?: number;
  cacheHitRatio: number;
  indexBuildDuration: number;
  llmCost: number;
  tokenUsage: number;
}

export interface AffectedSection {
  id: string;
  section: string;
  filePath: string;
  status: DocStatus;
  confidence: number;
  reason: string;
  lineStart: number;
  lineEnd: number;
  currentMarkdown: string;
  newMarkdown: string;
  oldCode: string;
  newCode: string;
  llmExplanation: string;
  changesCount: number;
}

export interface AICorrection {
  id: string;
  repository: string;
  section: string;
  reason: string;
  confidence: number;
  status: CorrectionStatus;
  createdAt: string;
  validationAccuracy: number;
  validationStyle: number;
  validationCompleteness: number;
}

export interface PullRequest {
  id: string;
  number: number;
  title: string;
  repository: string;
  branch: string;
  status: PRStatus;
  autoGenerated: boolean;
  createdAt: string;
  fixesCount: number;
  githubUrl: string;
  description: string;
}

export interface LogEntry {
  id: string;
  timestamp: string;
  level: LogLevel;
  message: string;
  phase: string;
  extra?: Record<string, unknown>;
}

export interface Notification {
  id: string;
  type: 'pr_created' | 'scan_finished' | 'review_needed' | 'repo_connected' | 'github_sync';
  title: string;
  description: string;
  timestamp: string;
  read: boolean;
  repository?: string;
}

export interface AnalyticsDataPoint {
  date: string;
  accuracy: number;
  fixes: number;
  health: number;
  confidence: number;
  falsePositive: number;
  processingTime: number;
  llmCost: number;
  tokenUsage: number;
}

// ---- Mock Data ----

export const REPOSITORIES: Repository[] = [
  {
    id: 'repo-1',
    name: 'api-gateway',
    fullName: 'acme-corp/api-gateway',
    language: 'TypeScript',
    languageColor: '#3178c6',
    avatar: 'AG',
    stars: 1247,
    health: 94,
    coverage: 87,
    lastScan: '2 minutes ago',
    branch: 'main',
    docSections: 142,
    codeChunks: 389,
  },
  {
    id: 'repo-2',
    name: 'ml-pipeline',
    fullName: 'acme-corp/ml-pipeline',
    language: 'Python',
    languageColor: '#3572A5',
    avatar: 'ML',
    stars: 834,
    health: 78,
    coverage: 63,
    lastScan: '18 minutes ago',
    branch: 'develop',
    docSections: 98,
    codeChunks: 271,
  },
  {
    id: 'repo-3',
    name: 'auth-service',
    fullName: 'acme-corp/auth-service',
    language: 'Go',
    languageColor: '#00ADD8',
    avatar: 'AS',
    stars: 592,
    health: 91,
    coverage: 92,
    lastScan: '1 hour ago',
    branch: 'main',
    docSections: 67,
    codeChunks: 183,
  },
  {
    id: 'repo-4',
    name: 'data-ingestion',
    fullName: 'acme-corp/data-ingestion',
    language: 'Python',
    languageColor: '#3572A5',
    avatar: 'DI',
    stars: 218,
    health: 65,
    coverage: 54,
    lastScan: '3 hours ago',
    branch: 'feature/kafka-integration',
    docSections: 44,
    codeChunks: 127,
  },
];

export const STAT_CARDS: StatCard[] = [
  {
    id: 'repos',
    label: 'Repositories Connected',
    value: 4,
    trend: 2,
    trendLabel: 'this month',
    sparkline: [1, 1, 2, 2, 3, 3, 4, 4],
    icon: 'GitBranch',
    color: '#3b82f6',
  },
  {
    id: 'docs',
    label: 'Documentation Sections',
    value: 351,
    trend: 12.4,
    trendLabel: 'this week',
    sparkline: [280, 295, 301, 318, 325, 338, 344, 351],
    icon: 'FileText',
    color: '#8b5cf6',
  },
  {
    id: 'chunks',
    label: 'Code Chunks Indexed',
    value: 970,
    trend: 8.7,
    trendLabel: 'this week',
    sparkline: [820, 845, 870, 890, 912, 938, 956, 970],
    icon: 'Code2',
    color: '#06b6d4',
  },
  {
    id: 'fixes',
    label: 'AI Fixes Generated',
    value: 128,
    trend: 23.1,
    trendLabel: 'this month',
    sparkline: [12, 24, 31, 48, 67, 89, 112, 128],
    icon: 'Wand2',
    color: '#22c55e',
  },
  {
    id: 'prs',
    label: 'Open Pull Requests',
    value: 7,
    trend: -14.3,
    trendLabel: 'vs last week',
    sparkline: [12, 11, 14, 10, 9, 8, 8, 7],
    icon: 'GitPullRequest',
    color: '#f59e0b',
  },
  {
    id: 'accuracy',
    label: 'Documentation Accuracy',
    value: '94.2%',
    trend: 3.8,
    trendLabel: 'vs last month',
    sparkline: [88, 89, 90, 91, 91, 92, 93, 94],
    icon: 'ShieldCheck',
    color: '#22c55e',
  },
];

export const SCAN_HISTORY: ScanRun[] = [
  {
    id: 'scan-001',
    repository: 'acme-corp/api-gateway',
    repoId: 'repo-1',
    status: 'completed',
    duration: 87,
    filesChanged: 14,
    meaningfulChanges: 9,
    sectionsChecked: 23,
    aiFixes: 4,
    progress: 100,
    startedAt: '2026-07-05T00:45:00Z',
    completedAt: '2026-07-05T00:46:27Z',
    baseSha: 'a3f82bc',
    headSha: 'e91d4f7',
    prNumber: 342,
    cacheHitRatio: 0.73,
    indexBuildDuration: 18.4,
    llmCost: 0.042,
    tokenUsage: 14200,
  },
  {
    id: 'scan-002',
    repository: 'acme-corp/ml-pipeline',
    repoId: 'repo-2',
    status: 'running',
    duration: 0,
    filesChanged: 6,
    meaningfulChanges: 4,
    sectionsChecked: 11,
    aiFixes: 1,
    progress: 67,
    startedAt: '2026-07-05T01:02:00Z',
    completedAt: '',
    baseSha: 'b7c19de',
    headSha: '2f0a8c4',
    cacheHitRatio: 0.61,
    indexBuildDuration: 0,
    llmCost: 0.018,
    tokenUsage: 6400,
  },
  {
    id: 'scan-003',
    repository: 'acme-corp/auth-service',
    repoId: 'repo-3',
    status: 'completed',
    duration: 52,
    filesChanged: 5,
    meaningfulChanges: 3,
    sectionsChecked: 8,
    aiFixes: 0,
    progress: 100,
    startedAt: '2026-07-04T23:20:00Z',
    completedAt: '2026-07-04T23:20:52Z',
    baseSha: 'c4a71ef',
    headSha: '9b3d2a1',
    cacheHitRatio: 0.89,
    indexBuildDuration: 9.2,
    llmCost: 0.021,
    tokenUsage: 7100,
  },
  {
    id: 'scan-004',
    repository: 'acme-corp/data-ingestion',
    repoId: 'repo-4',
    status: 'failed',
    duration: 23,
    filesChanged: 18,
    meaningfulChanges: 12,
    sectionsChecked: 0,
    aiFixes: 0,
    progress: 0,
    startedAt: '2026-07-04T22:10:00Z',
    completedAt: '2026-07-04T22:10:23Z',
    baseSha: 'd2e94ba',
    headSha: 'f01c3e8',
    cacheHitRatio: 0.0,
    indexBuildDuration: 0,
    llmCost: 0,
    tokenUsage: 0,
  },
  {
    id: 'scan-005',
    repository: 'acme-corp/api-gateway',
    repoId: 'repo-1',
    status: 'completed',
    duration: 74,
    filesChanged: 8,
    meaningfulChanges: 5,
    sectionsChecked: 14,
    aiFixes: 2,
    progress: 100,
    startedAt: '2026-07-04T20:30:00Z',
    completedAt: '2026-07-04T20:31:14Z',
    baseSha: 'e1f5092',
    headSha: 'a3f82bc',
    prNumber: 339,
    cacheHitRatio: 0.81,
    indexBuildDuration: 12.1,
    llmCost: 0.031,
    tokenUsage: 10500,
  },
];

export const AFFECTED_SECTIONS: AffectedSection[] = [
  {
    id: 'sec-001',
    section: 'Authentication > JWT Token Validation',
    filePath: 'docs/api/authentication.md',
    status: 'auto_fixed',
    confidence: 0.96,
    reason: 'Function signature changed: `validateToken(token)` → `validateToken(token, options?)`',
    lineStart: 42,
    lineEnd: 78,
    currentMarkdown: `## JWT Token Validation

The \`validateToken\` function verifies the authenticity of JWT tokens issued by the authentication service.

### Parameters

| Parameter | Type | Description |
|-----------|------|-------------|
| \`token\` | \`string\` | The JWT token string to validate |

### Example

\`\`\`typescript
const result = await validateToken(token);
if (result.valid) {
  // Proceed with authenticated request
}
\`\`\``,
    newMarkdown: `## JWT Token Validation

The \`validateToken\` function verifies the authenticity of JWT tokens issued by the authentication service.

### Parameters

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
| \`token\` | \`string\` | Yes | The JWT token string to validate |
| \`options\` | \`ValidateOptions\` | No | Optional validation configuration |

### Options

| Option | Type | Default | Description |
|--------|------|---------|-------------|
| \`algorithm\` | \`string\` | \`'RS256'\` | JWT signing algorithm |
| \`issuer\` | \`string\` | \`undefined\` | Expected token issuer |
| \`audience\` | \`string[]\` | \`[]\` | Expected token audience |

### Example

\`\`\`typescript
const result = await validateToken(token, {
  algorithm: 'RS256',
  issuer: 'https://auth.acme-corp.com',
});
if (result.valid) {
  // Proceed with authenticated request
}
\`\`\``,
    oldCode: `export async function validateToken(token: string): Promise<ValidationResult> {
  const decoded = jwt.verify(token, process.env.JWT_SECRET!);
  return { valid: true, payload: decoded };
}`,
    newCode: `export interface ValidateOptions {
  algorithm?: string;
  issuer?: string;
  audience?: string[];
}

export async function validateToken(
  token: string,
  options?: ValidateOptions
): Promise<ValidationResult> {
  const verifyOptions: jwt.VerifyOptions = {
    algorithms: [options?.algorithm ?? 'RS256'],
    issuer: options?.issuer,
    audience: options?.audience,
  };
  const decoded = jwt.verify(token, process.env.JWT_PUBLIC_KEY!, verifyOptions);
  return { valid: true, payload: decoded };
}`,
    llmExplanation: 'The function signature was updated to accept an optional `options` parameter of type `ValidateOptions`. The documentation only described the original single-parameter signature and did not mention the new options interface. The updated documentation adds the options table and updates the code example to demonstrate the new API.',
    changesCount: 3,
  },
  {
    id: 'sec-002',
    section: 'Rate Limiting > Configuration Schema',
    filePath: 'docs/api/rate-limiting.md',
    status: 'needs_review',
    confidence: 0.71,
    reason: 'Pydantic schema field `windowMs` renamed to `windowSeconds` with type change from `number` to `number`',
    lineStart: 15,
    lineEnd: 44,
    currentMarkdown: `## Rate Limiting Configuration

Configure rate limiting using the \`RateLimitConfig\` schema.

\`\`\`json
{
  "windowMs": 60000,
  "maxRequests": 100,
  "skipFailedRequests": false
}
\`\`\``,
    newMarkdown: `## Rate Limiting Configuration

Configure rate limiting using the \`RateLimitConfig\` schema.

\`\`\`json
{
  "windowSeconds": 60,
  "maxRequests": 100,
  "skipFailedRequests": false,
  "keyGenerator": "ip"
}
\`\`\``,
    oldCode: `class RateLimitConfig(BaseModel):
    windowMs: int = 60000
    maxRequests: int = 100
    skipFailedRequests: bool = False`,
    newCode: `class RateLimitConfig(BaseModel):
    windowSeconds: int = 60
    maxRequests: int = 100
    skipFailedRequests: bool = False
    keyGenerator: Literal['ip', 'user', 'api_key'] = 'ip'`,
    llmExplanation: 'The configuration field `windowMs` (milliseconds) was renamed to `windowSeconds` (seconds) and a new `keyGenerator` field was added. The documentation examples still show the old field names. This is a breaking change that may cause confusion for users reading the documentation.',
    changesCount: 2,
  },
  {
    id: 'sec-003',
    section: 'Webhook Events > Payload Structure',
    filePath: 'docs/webhooks/events.md',
    status: 'verified',
    confidence: 0.98,
    reason: 'Internal implementation change only — public API surface unchanged',
    lineStart: 88,
    lineEnd: 132,
    currentMarkdown: `## Webhook Payload Structure

All webhook events share a common envelope structure.

\`\`\`json
{
  "id": "evt_01HABCDEF12345",
  "type": "user.created",
  "timestamp": "2026-07-05T00:00:00Z",
  "data": { ... }
}
\`\`\``,
    newMarkdown: `## Webhook Payload Structure

All webhook events share a common envelope structure.

\`\`\`json
{
  "id": "evt_01HABCDEF12345",
  "type": "user.created",
  "timestamp": "2026-07-05T00:00:00Z",
  "data": { ... }
}
\`\`\``,
    oldCode: `def dispatch_event(event_type: str, data: dict) -> None:
    payload = build_payload(event_type, data)
    _send_to_queue(payload)`,
    newCode: `async def dispatch_event(event_type: str, data: dict) -> None:
    payload = build_payload(event_type, data)
    await _send_to_queue_async(payload)`,
    llmExplanation: 'The function was converted to async but the public webhook payload structure remains identical. Documentation accurately describes the webhook format and does not need updating.',
    changesCount: 0,
  },
  {
    id: 'sec-004',
    section: 'CLI Reference > scan command',
    filePath: 'docs/cli/reference.md',
    status: 'auto_fixed',
    confidence: 0.89,
    reason: 'New CLI flag `--parallel` added to `scan` command',
    lineStart: 201,
    lineEnd: 245,
    currentMarkdown: `## scan

Run a documentation scan against a repository.

\`\`\`bash
docs-healer scan --repo owner/repo --base main --head feature/my-branch
\`\`\`

### Flags

| Flag | Type | Description |
|------|------|-------------|
| \`--repo\` | string | Repository in owner/repo format |
| \`--base\` | string | Base branch or SHA |
| \`--head\` | string | Head branch or SHA |`,
    newMarkdown: `## scan

Run a documentation scan against a repository.

\`\`\`bash
docs-healer scan --repo owner/repo --base main --head feature/my-branch --parallel 4
\`\`\`

### Flags

| Flag | Type | Default | Description |
|------|------|---------|-------------|
| \`--repo\` | string | — | Repository in owner/repo format |
| \`--base\` | string | — | Base branch or SHA |
| \`--head\` | string | — | Head branch or SHA |
| \`--parallel\` | number | \`1\` | Number of parallel LLM verification workers |`,
    oldCode: `@click.command()
@click.option('--repo', required=True)
@click.option('--base', required=True)
@click.option('--head', required=True)
def scan(repo: str, base: str, head: str):
    run_scan(repo, base, head)`,
    newCode: `@click.command()
@click.option('--repo', required=True)
@click.option('--base', required=True)
@click.option('--head', required=True)
@click.option('--parallel', default=1, type=int)
def scan(repo: str, base: str, head: str, parallel: int):
    run_scan(repo, base, head, parallel_workers=parallel)`,
    llmExplanation: 'A new `--parallel` CLI flag was added that controls the number of concurrent LLM verification workers. The documentation flag table did not include this option and the example command did not demonstrate its usage.',
    changesCount: 2,
  },
];

export const AI_CORRECTIONS: AICorrection[] = [
  {
    id: 'corr-001',
    repository: 'acme-corp/api-gateway',
    section: 'Authentication > JWT Token Validation',
    reason: 'Function signature changed with optional parameters',
    confidence: 0.96,
    status: 'approved',
    createdAt: '2026-07-05T00:46:27Z',
    validationAccuracy: 0.97,
    validationStyle: 0.94,
    validationCompleteness: 0.95,
  },
  {
    id: 'corr-002',
    repository: 'acme-corp/api-gateway',
    section: 'CLI Reference > scan command',
    reason: 'New --parallel flag added to CLI',
    confidence: 0.89,
    status: 'pending',
    createdAt: '2026-07-05T00:46:27Z',
    validationAccuracy: 0.91,
    validationStyle: 0.88,
    validationCompleteness: 0.92,
  },
  {
    id: 'corr-003',
    repository: 'acme-corp/auth-service',
    section: 'OAuth2 > Token Refresh Flow',
    reason: 'Refresh token expiry changed from 7d to 30d',
    confidence: 0.94,
    status: 'pending',
    createdAt: '2026-07-04T23:20:52Z',
    validationAccuracy: 0.95,
    validationStyle: 0.93,
    validationCompleteness: 0.91,
  },
  {
    id: 'corr-004',
    repository: 'acme-corp/ml-pipeline',
    section: 'Training > DataLoader Parameters',
    reason: 'batch_size default changed from 32 to 64',
    confidence: 0.82,
    status: 'rejected',
    createdAt: '2026-07-04T22:15:00Z',
    validationAccuracy: 0.84,
    validationStyle: 0.79,
    validationCompleteness: 0.81,
  },
];

export const PULL_REQUESTS: PullRequest[] = [
  {
    id: 'pr-001',
    number: 342,
    title: 'docs: auto-fix JWT validation and CLI scan documentation',
    repository: 'acme-corp/api-gateway',
    branch: 'docs-healer/fix-pr-341-1751760387',
    status: 'open',
    autoGenerated: true,
    createdAt: '2026-07-05T00:46:29Z',
    fixesCount: 2,
    githubUrl: 'https://github.com/acme-corp/api-gateway/pull/342',
    description: 'Automated documentation fixes for PR #341 covering JWT token validation and CLI reference updates.',
  },
  {
    id: 'pr-002',
    number: 339,
    title: 'docs: update error handling and middleware configuration docs',
    repository: 'acme-corp/api-gateway',
    branch: 'docs-healer/fix-pr-337-1751741400',
    status: 'merged',
    autoGenerated: true,
    createdAt: '2026-07-04T20:31:16Z',
    fixesCount: 2,
    githubUrl: 'https://github.com/acme-corp/api-gateway/pull/339',
    description: 'Automated documentation fixes for PR #337 covering error handling middleware.',
  },
  {
    id: 'pr-003',
    number: 28,
    title: 'docs: fix OAuth2 token refresh expiry documentation',
    repository: 'acme-corp/auth-service',
    branch: 'docs-healer/fix-pr-27-1751720800',
    status: 'open',
    autoGenerated: true,
    createdAt: '2026-07-04T23:20:55Z',
    fixesCount: 1,
    githubUrl: 'https://github.com/acme-corp/auth-service/pull/28',
    description: 'Automated documentation fix for PR #27 covering OAuth2 refresh token configuration.',
  },
];

export const ANALYTICS_DATA: AnalyticsDataPoint[] = [
  { date: 'Jun 29', accuracy: 88.4, fixes: 8, health: 76, confidence: 0.81, falsePositive: 14.2, processingTime: 112, llmCost: 0.18, tokenUsage: 61000 },
  { date: 'Jun 30', accuracy: 89.1, fixes: 11, health: 78, confidence: 0.83, falsePositive: 12.8, processingTime: 98, llmCost: 0.22, tokenUsage: 74000 },
  { date: 'Jul 01', accuracy: 90.6, fixes: 9, health: 80, confidence: 0.84, falsePositive: 11.4, processingTime: 89, llmCost: 0.19, tokenUsage: 64000 },
  { date: 'Jul 02', accuracy: 91.2, fixes: 14, health: 82, confidence: 0.86, falsePositive: 10.1, processingTime: 94, llmCost: 0.27, tokenUsage: 91000 },
  { date: 'Jul 03', accuracy: 92.0, fixes: 18, health: 83, confidence: 0.87, falsePositive: 9.3, processingTime: 87, llmCost: 0.31, tokenUsage: 105000 },
  { date: 'Jul 04', accuracy: 93.5, fixes: 22, health: 87, confidence: 0.89, falsePositive: 8.7, processingTime: 81, llmCost: 0.39, tokenUsage: 131000 },
  { date: 'Jul 05', accuracy: 94.2, fixes: 17, health: 89, confidence: 0.91, falsePositive: 7.9, processingTime: 76, llmCost: 0.35, tokenUsage: 118000 },
];

export const MOCK_LOGS: LogEntry[] = [
  { id: 'log-001', timestamp: '2026-07-05T00:45:00Z', level: 'info', message: 'Starting Docs Healer system', phase: 'parsing', extra: { api_call_count: 0 } },
  { id: 'log-002', timestamp: '2026-07-05T00:45:01Z', level: 'info', message: 'Loaded valid index from cache', phase: 'indexing', extra: { api_call_count: 0 } },
  { id: 'log-003', timestamp: '2026-07-05T00:45:02Z', level: 'info', message: 'Starting Pull Request verification workflow for PR #341', phase: 'parsing' },
  { id: 'log-004', timestamp: '2026-07-05T00:45:03Z', level: 'info', message: 'Extracting git diff between a3f82bc and e91d4f7', phase: 'parsing', extra: { base_sha: 'a3f82bc', head_sha: 'e91d4f7' } },
  { id: 'log-005', timestamp: '2026-07-05T00:45:05Z', level: 'info', message: 'Git diff parsing complete. Found 14 changed files.', phase: 'parsing', extra: { meaningful_changes_count: 9 } },
  { id: 'log-006', timestamp: '2026-07-05T00:45:06Z', level: 'info', message: 'Mapped code changes to 9 affected code chunks.', phase: 'parsing' },
  { id: 'log-007', timestamp: '2026-07-05T00:45:07Z', level: 'info', message: 'Query for affected sections completed in 0.0004s', phase: 'indexing', extra: { queried_chunks_count: 9, found_sections_count: 23 } },
  { id: 'log-008', timestamp: '2026-07-05T00:45:08Z', level: 'info', message: 'Running LLM staleness checks on 23 doc sections...', phase: 'verification' },
  { id: 'log-009', timestamp: '2026-07-05T00:45:12Z', level: 'info', message: 'Verifying staleness for section: docs/api/authentication.md::Authentication > JWT Token Validation', phase: 'verification' },
  { id: 'log-010', timestamp: '2026-07-05T00:45:18Z', level: 'info', message: 'Doc section identified as stale: docs/api/authentication.md::Authentication > JWT Token Validation', phase: 'verification' },
  { id: 'log-011', timestamp: '2026-07-05T00:45:19Z', level: 'info', message: 'Generating correction for section: docs/api/authentication.md::Authentication > JWT Token Validation', phase: 'correction' },
  { id: 'log-012', timestamp: '2026-07-05T00:45:28Z', level: 'info', message: 'Correction generation finished. Validation: passed. Auto-fix eligible: true.', phase: 'correction', extra: { section: 'JWT Token Validation' } },
  { id: 'log-013', timestamp: '2026-07-05T00:45:32Z', level: 'warning', message: 'Rate limit encountered on LLM API call. Retrying in 2s (Attempt 1/5)...', phase: 'verification' },
  { id: 'log-014', timestamp: '2026-07-05T00:45:48Z', level: 'info', message: 'Verifying staleness for section: docs/api/rate-limiting.md::Rate Limiting > Configuration Schema', phase: 'verification' },
  { id: 'log-015', timestamp: '2026-07-05T00:45:55Z', level: 'info', message: 'Doc section identified as stale: docs/api/rate-limiting.md::Rate Limiting > Configuration Schema', phase: 'verification' },
  { id: 'log-016', timestamp: '2026-07-05T00:45:57Z', level: 'info', message: 'Generating correction for section: docs/api/rate-limiting.md::Rate Limiting > Configuration Schema', phase: 'correction' },
  { id: 'log-017', timestamp: '2026-07-05T00:46:04Z', level: 'warning', message: 'Correction confidence 0.71 below auto_fix threshold 0.85. Flagging for review.', phase: 'correction' },
  { id: 'log-018', timestamp: '2026-07-05T00:46:20Z', level: 'info', message: 'Generating auto-fix PR for 2 sections...', phase: 'github' },
  { id: 'log-019', timestamp: '2026-07-05T00:46:22Z', level: 'info', message: 'Committing documentation changes', phase: 'github' },
  { id: 'log-020', timestamp: '2026-07-05T00:46:24Z', level: 'info', message: 'Pushing branch docs-healer/fix-pr-341-1751760387 to remote', phase: 'github' },
  { id: 'log-021', timestamp: '2026-07-05T00:46:27Z', level: 'info', message: 'Pull request created successfully: #342', phase: 'github', extra: { pr_number: 342 } },
  { id: 'log-022', timestamp: '2026-07-05T00:46:27Z', level: 'info', message: 'Docs Healer workflow complete in 87.41s.', phase: 'github', extra: { stale_sections_count: 4, auto_fixed_count: 2, flagged_count: 1, total_execution_time: 87.41 } },
];

export const NOTIFICATIONS: Notification[] = [
  { id: 'notif-001', type: 'pr_created', title: 'Auto-fix PR Created', description: 'PR #342 created for acme-corp/api-gateway with 2 doc fixes', timestamp: '2026-07-05T00:46:29Z', read: false, repository: 'acme-corp/api-gateway' },
  { id: 'notif-002', type: 'scan_finished', title: 'Scan Completed', description: 'Scan of acme-corp/api-gateway completed in 87s — 4 fixes generated', timestamp: '2026-07-05T00:46:27Z', read: false, repository: 'acme-corp/api-gateway' },
  { id: 'notif-003', type: 'review_needed', title: 'Manual Review Required', description: 'Rate Limiting > Configuration Schema needs review (confidence: 71%)', timestamp: '2026-07-05T00:46:05Z', read: false, repository: 'acme-corp/api-gateway' },
  { id: 'notif-004', type: 'scan_finished', title: 'Scan Completed', description: 'Scan of acme-corp/auth-service completed in 52s — all docs verified', timestamp: '2026-07-04T23:20:52Z', read: true, repository: 'acme-corp/auth-service' },
  { id: 'notif-005', type: 'github_sync', title: 'GitHub Sync Complete', description: '4 repositories synchronized. Index rebuilt in 18.4s', timestamp: '2026-07-04T22:00:00Z', read: true },
];

export const PIPELINE_STAGES = [
  { id: 'repo', label: 'Repository', icon: 'GitBranch', description: 'Connect GitHub repo and fetch PR diff' },
  { id: 'code_parser', label: 'Code Parser', icon: 'Code2', description: 'AST analysis of Python & TypeScript files' },
  { id: 'doc_parser', label: 'Doc Parser', icon: 'FileText', description: 'Split markdown into semantic sections' },
  { id: 'embedding', label: 'Embedding Engine', icon: 'Cpu', description: 'Generate semantic vectors via OpenAI API' },
  { id: 'graph', label: 'Code-to-Docs Graph', icon: 'Network', description: 'Build semantic link graph with confidence scores' },
  { id: 'diff', label: 'Git Diff Analysis', icon: 'GitCompare', description: 'Classify meaningful changes by type' },
  { id: 'llm', label: 'LLM Verification', icon: 'Brain', description: 'GPT-4o staleness verification with structured output' },
  { id: 'repair', label: 'Repair Engine', icon: 'Wand2', description: 'Generate & validate corrected documentation' },
  { id: 'pr', label: 'GitHub PR', icon: 'GitPullRequest', description: 'Push branch and open auto-fix pull request' },
];
