export type ScanStatus = 'running' | 'completed' | 'failed' | 'queued';
export type DocStatus = 'verified' | 'needs_review' | 'auto_fixed';
export type CorrectionStatus = 'pending' | 'approved' | 'rejected';
export type PRStatus = 'open' | 'merged' | 'closed';
export type LogLevel = 'info' | 'warning' | 'error';
export type PipelineStageStatus = 'idle' | 'active' | 'done' | 'error';

export interface Repository {
  id: string;
  name: string;
  fullName: string;
  language: string;
  languageColor: string;
  avatar: string;
  stars: number;
  health: number;
  coverage: number;
  lastScan: string;
  branch: string;
  docSections: number;
  codeChunks: number;
}

export interface StatCard {
  id: string;
  label: string;
  value: string | number;
  trend: number;
  trendLabel: string;
  sparkline: number[];
  icon: string;
  color: string;
}

export interface ScanRun {
  id: string;
  repository: string;
  repoId: string;
  status: ScanStatus;
  duration: number;
  filesChanged: number;
  meaningfulChanges: number;
  sectionsChecked: number;
  aiFixes: number;
  progress: number;
  startedAt: string;
  completedAt: string;
  baseSha: string;
  headSha: string;
  prNumber?: number;
  cacheHitRatio: number;
  indexBuildDuration: number;
  llmCost: number;
  tokenUsage: number;
}

export interface AffectedSection {
  id: string;
  section: string;
  filePath: string;
  status: DocStatus;
  confidence: number;
  reason: string;
  lineStart: number;
  lineEnd: number;
  currentMarkdown: string;
  newMarkdown: string;
  oldCode: string;
  newCode: string;
  llmExplanation: string;
  changesCount: number;
}

export interface AICorrection {
  id: string;
  repository: string;
  section: string;
  reason: string;
  confidence: number;
  status: CorrectionStatus;
  createdAt: string;
  validationAccuracy: number;
  validationStyle: number;
  validationCompleteness: number;
}

export interface PullRequest {
  id: string;
  number: number;
  title: string;
  repository: string;
  branch: string;
  status: PRStatus;
  autoGenerated: boolean;
  createdAt: string;
  fixesCount: number;
  githubUrl: string;
  description: string;
}

export interface LogEntry {
  id: string;
  timestamp: string;
  level: LogLevel;
  message: string;
  phase: string;
  extra?: Record<string, unknown>;
}

export interface Notification {
  id: string;
  type: 'pr_created' | 'scan_finished' | 'review_needed' | 'repo_connected' | 'github_sync';
  title: string;
  description: string;
  timestamp: string;
  read: boolean;
  repository?: string;
}

export interface AnalyticsDataPoint {
  date: string;
  accuracy: number;
  fixes: number;
  health: number;
  confidence: number;
  falsePositive: number;
  processingTime: number;
  llmCost: number;
  tokenUsage: number;
}

export interface ConfidenceBucket {
  name: string;
  value: number;
  color: string;
}

export interface AnalyticsResponse {
  dataPoints: AnalyticsDataPoint[];
  confidenceDistribution: ConfidenceBucket[];
}

export interface PipelineStage {
  id: string;
  label: string;
  icon: string;
  description: string;
}

export interface PipelineProgress {
  isRunning: boolean;
  activeStageIndex: number;
  stageStatuses: PipelineStageStatus[];
  stages: PipelineStage[];
  message?: string;
}

export interface DashboardSummary {
  statCards: StatCard[];
  notifications: Notification[];
  repositories: Repository[];
  heroStats: {
    repositories: number;
    docSections: number;
    codeChunks: number;
    aiFixes: number;
  };
  counts: {
    pendingCorrections: number;
    openPullRequests: number;
  };
  user: {
    name: string;
    email: string;
    initials: string;
    githubUsername?: string;
    githubConnected: boolean;
  } | null;
}

export interface DocumentationSummary {
  totalSections: number;
  verified: number;
  needsReview: number;
  autoFixed: number;
  sections: AffectedSection[];
}

export interface SettingsData {
  github: {
    connected: boolean;
    tokenMasked: string;
    autoFixPrs: boolean;
    webhookEvents: boolean;
  };
  ai: {
    llmModel: string;
    embeddingModel: string;
    autoFixThreshold: number;
    parallelWorkers: number;
  };
  notifications: {
    email: boolean;
    slack: boolean;
    slackWebhookUrl: string;
    notifyOnReview: boolean;
  };
  security: {
    webhookSecretMasked: string;
    rateLimit: string;
    auditLogging: boolean;
    cacheTtlHours: number;
  };
  githubPermissions: Array<{ scope: string; desc: string; granted: boolean }>;
}

export interface ScanRequest {
  repositoryId: string;
}

export interface ScanResponse {
  scanId: string;
  status: ScanStatus;
}

export class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
    public body?: unknown,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}
